name: video-processor

services:
  worker:
    build:
      context: .
    env_file:
      - .env
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - PROCESSING_JOBS_TABLE_NAME=fiapx-dev-videos-db
      - SQS_QUEUE_NAMES_VIDEO_PROCESSING_REQUESTED=fiapx-dev-video-processing-requested
      - SQS_QUEUE_NAMES_VIDEO_PROCESSING_COMPLETED=fiapx-dev-video-processing-completed
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs,s3,dynamodb
      - DYNAMODB_SHARE_DB=1
      - DYNAMODB_IN_MEMORY=1
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: 'curl -f http://localhost:4566/_localstack/health'
      interval: 2s
      timeout: 5s
      retries: 10
