name: video-processor

services:
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs,s3,dynamodb
      - DYNAMODB_SHARE_DB=1
      - DYNAMODB_IN_MEMORY=1
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: 'curl -f http://localhost:4566/_localstack/health'
      interval: 2s
      timeout: 5s
      retries: 10
