apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-processor-config
data:
  AWS_REGION: us-east-1
  AWS_ENDPOINT: http://localstack:4566
  SQS_QUEUE_NAME: video-processing
  SQS_QUEUE_URL: http://localstack:4566/000000000000/video-processing
  S3_BUCKET: videos
  FRAME_PREFIX: frames