apiVersion: v1
kind: Secret
metadata:
  name: fiapx-processor-aws
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: fiapx-processor-aws-auth
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: fiapx-processor-aws
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: fiapx-processor-aws
      key: AWS_SECRET_ACCESS_KEY