apiVersion: keda.sh/v1alpha1
kind: ScaledJob

metadata:
  name: {{ .Values.app.name }}

spec:
  maxReplicaCount: {{ .Values.limits.maxParallelJobs | int64 }}
  jobTargetRef:
    template:
      spec:
        containers:
          - name: {{ .Values.app.name }}
            image: {{ .Values.image.repository | required "Parameter image.repository is required." }}:{{ .Values.image.tag }}
            imagePullPolicy: Always

            resources:
              requests:
                cpu: {{ .Values.job.resources.requests.cpu | quote }}
                memory: {{ .Values.job.resources.requests.memory | quote }}
              limits:
                cpu: {{ .Values.job.resources.limits.cpu | quote }}
                memory: {{ .Values.job.resources.limits.memory | quote }}

            envFrom:
              - configMapRef:
                  name: {{ .Values.app.name }}-configs

            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: secret-access-key
              - name: AWS_SESSION_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: session-token
              - name: DD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-datadog
                    key: api-key
                    optional: true

        restartPolicy: Never
        terminationGracePeriodSeconds: {{ .Values.job.terminationGracePeriodSeconds }}

  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: {{ .Values.queue.url | required "Parameter queue.url is required." | quote }}
        queueLength: "1"
        awsRegion: {{ .Values.aws.region | quote }}
      authenticationRef:
        name: {{ .Values.app.name }}-keda-auth
